/**
 * @author Codex
 * @description Covers bridge ownership, fail-closed delegation and real readonly child retrieval boundaries.
 */
import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, mkdir, readFile, writeFile, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { DefaultResourceLoader, SettingsManager } from '@earendil-works/pi-coding-agent';
import { createSubagentBridgeExtension } from '../dist/extensions/subagent-bridge/index.js';
import { startChildAdmission, verifyChildAdmission } from '../dist/extensions/subagent-bridge/admission.js';
import { ensureChildEntry, ensureExplorerAgent } from '../dist/extensions/subagent-bridge/resources.js';
import { createPermissionModeService } from '../dist/extensions/permission-system/sdk/index.js';
import { loadDefaultPermissionConfiguration } from '../dist/extensions/permission-system/lib/default-configuration.js';
import { createScopedChildExtension } from '../dist/extensions/subagent-bridge/child-entry.js';
import { inspectDelegatedTools } from '../dist/extensions/subagent-bridge/diagnostics.js';
import { CHILD_TOOLS } from '../dist/extensions/subagent-bridge/contracts.js';
import { createKnowledgeChildExtension } from '../dist/extensions/knowledge/extension/child-entry.js';
import { createMemoryChildExtension } from '../dist/extensions/memory/extension/child-entry.js';
import { createMemoryService } from '../dist/extensions/memory/sdk/index.js';

/**
 * Record public Pi surfaces and permit lifecycle invocation without a model.
 */
function harness(active = [...CHILD_TOOLS]) {
  const events = new Map(),
    tools = new Map(),
    commands = new Map(),
    messages = [];
  const pi = {
    on: (name, fn) => events.set(name, fn),
    registerTool: (tool) => tools.set(tool.name, tool),
    getActiveTools: () => active,
    setActiveTools: (names) => active.splice(0, active.length, ...names),
    getAllTools: () => CHILD_TOOLS.map((name) => ({ name })),
    registerCommand: (name, definition) => commands.set(name, definition),
    sendMessage: (message) => messages.push(message),
  };
  return { pi, events, tools, active, commands, messages };
}

/**
 * Isolate bridge lifecycle tests from interactive confirmation defaults.
 */
function fullPermissions() {
  const service = createPermissionModeService({ agentDir: join(tmpdir(), 'octopus-test-no-config') });
  service.setMode('full');
  return service;
}

/**
 * Supply the same serialized policy contract generated by a real parent.
 */
function permissionSnapshot(mode = 'full') {
  return { version: 2, cwd: process.cwd(), mode, configuration: loadDefaultPermissionConfiguration() };
}

test('bridge replaces scoped snapshots, serializes refreshes and releases ownership on shutdown', async () => {
  const { pi, events, active } = harness();
  const registry = new Map(),
    scopes = [];
  let session = 'file-a',
    branch = [],
    registrations = 0;
  const ctx = {
    cwd: process.cwd(),
    isProjectTrusted: () => false,
    sessionManager: { getSessionFile: () => session, getSessionId: () => 'uuid', getBranch: () => branch },
  };
  createSubagentBridgeExtension(
    { agentDir: '/agent', workspaceId: 'workspace-a', permissionService: fullPermissions() },
    {
      loadRequiredChildApi: async () => ({
        registerRequiredChildExtensions: ({ sessionId, extensions }) => {
          assert.equal(registry.has(sessionId), false);
          registrations++;
          registry.set(sessionId, extensions);
          return { dispose: () => registry.delete(sessionId) };
        },
      }),
      ensureExplorerAgent: async () => {},
      ensureChildEntry: async (scope) => {
        scopes.push(scope);
        return '/entry.mjs';
      },
    }
  )(pi);
  await events.get('session_start')({}, ctx);
  await Promise.all([
    events.get('tool_call')({ toolName: 'subagent' }, ctx),
    events.get('tool_call')({ toolName: 'subagent' }, ctx),
  ]);
  assert.equal(registrations, 2);
  branch = [
    {
      type: 'custom',
      customType: 'octopus-knowledge-mode',
      data: { version: 1, enabled: true, collectionIds: ['selected'] },
    },
  ];
  await events.get('tool_call')({ toolName: 'subagent' }, ctx);
  assert.deepEqual(scopes.at(-1).collectionIds, ['selected']);
  branch[0].data.enabled = false;
  await events.get('tool_call')({ toolName: 'subagent' }, ctx);
  assert.deepEqual(scopes.at(-1).tools, [
    'ocr_image',
    'embed_text',
    'rerank_documents',
    'memory_recall',
    'memory_read',
  ]);
  active.splice(0, active.length, 'memory_read', 'memory_recall');
  session = 'file-b';
  await events.get('session_start')({}, ctx);
  assert.deepEqual([...registry.keys()], ['file-b', 'uuid']);
  assert.deepEqual(scopes.at(-1).tools, ['memory_recall', 'memory_read']);
  await events.get('session_shutdown')();
  await events.get('session_shutdown')();
  assert.equal(registry.size, 0);
  await events.get('session_start')({}, ctx);
  assert.equal(registry.size, 2);
  branch[0].data = {};
  assert.equal((await events.get('tool_call')({ toolName: 'subagent' }, ctx)).block, true);
  assert.equal(registry.size, 2); // Retained entry enforces admission on slash/API paths too.
  await events.get('session_shutdown')();
});

test('startup error cannot allow an unregistered subagent call', async () => {
  const { pi, events } = harness();
  createSubagentBridgeExtension(
    { agentDir: '/missing', workspaceId: 'w', permissionService: fullPermissions() },
    {
      loadRequiredChildApi: async () => {
        throw new Error('missing package');
      },
      ensureChildEntry: async () => assert.fail(),
      ensureExplorerAgent: async () => assert.fail(),
    }
  )(pi);
  const ctx = {
    cwd: process.cwd(),
    isProjectTrusted: () => false,
    sessionManager: { getBranch: () => [], getSessionFile: () => undefined, getSessionId: () => 'uuid' },
  };
  await assert.rejects(events.get('session_start')({}, ctx), /missing package/);
  assert.equal((await events.get('tool_call')({ toolName: 'subagent' }, ctx)).block, true);
  assert.equal(await events.get('tool_call')({ toolName: 'read' }, ctx), undefined);
});

test('second identity registration failure rolls back the first and can recover', async () => {
  const { pi, events } = harness();
  const registered = new Set();
  let fail = true;
  createSubagentBridgeExtension(
    { agentDir: '/agent', workspaceId: 'w', permissionService: fullPermissions() },
    {
      loadRequiredChildApi: async () => ({
        registerRequiredChildExtensions: ({ sessionId }) => {
          if (sessionId === 'uuid' && fail) throw new Error('duplicate uuid');
          registered.add(sessionId);
          return { dispose: () => registered.delete(sessionId) };
        },
      }),
      ensureChildEntry: async () => '/entry.mjs',
      ensureExplorerAgent: async () => {},
    }
  )(pi);
  const ctx = {
    cwd: process.cwd(),
    isProjectTrusted: () => false,
    sessionManager: { getBranch: () => [], getSessionFile: () => '/session', getSessionId: () => 'uuid' },
  };
  await assert.rejects(events.get('session_start')({}, ctx), /duplicate uuid/);
  assert.equal(registered.size, 0);
  fail = false;
  assert.equal(await events.get('tool_call')({ toolName: 'subagent' }, ctx), undefined);
  assert.equal(registered.size, 2);
  await events.get('session_shutdown')();
  assert.equal(registered.size, 0);
});

test('shutdown during resource preparation cannot publish a late registration', async () => {
  const { pi, events } = harness();
  let release, entered;
  const started = new Promise((resolve) => {
    entered = resolve;
  });
  createSubagentBridgeExtension(
    { agentDir: '/agent', workspaceId: 'w', permissionService: fullPermissions() },
    {
      loadRequiredChildApi: async () => ({
        registerRequiredChildExtensions: () => assert.fail('late registration'),
      }),
      ensureExplorerAgent: async () => {},
      ensureChildEntry: () => {
        entered();
        return new Promise((resolve) => {
          release = resolve;
        });
      },
    }
  )(pi);
  const ctx = {
    cwd: process.cwd(),
    isProjectTrusted: () => false,
    sessionManager: { getBranch: () => [], getSessionFile: () => '/session', getSessionId: () => 'uuid' },
  };
  const startup = events.get('session_start')({}, ctx);
  const rejected = assert.rejects(startup, /closed/);
  await started;
  const shutdown = events.get('session_shutdown')();
  release('/entry.mjs');
  await Promise.all([shutdown, rejected]);
});

test('immutable generated entry loads through Pi and honors parent tool restrictions', async (t) => {
  const admission = await startChildAdmission(async () => true);
  t.after(() => admission.close());
  const descriptor = admission.descriptor('test');
  const root = await mkdtemp(join(tmpdir(), 'octopus-child-load-'));
  const scope = {
    permissions: permissionSnapshot(),
    agentDir: root,
    workspaceId: 'workspace',
    collectionIds: ['one'],
    tools: [...CHILD_TOOLS],
  };
  const path = await ensureChildEntry(scope, descriptor);
  assert.equal(await ensureChildEntry(scope, descriptor), path);
  assert.deepEqual(
    await Promise.all(Array.from({ length: 4 }, () => ensureChildEntry(scope, descriptor))),
    Array(4).fill(path)
  );
  const loader = new DefaultResourceLoader({
    cwd: root,
    agentDir: root,
    settingsManager: SettingsManager.inMemory({ packages: [] }),
    additionalExtensionPaths: [path],
    noExtensions: true,
    noSkills: true,
    noPromptTemplates: true,
    noThemes: true,
  });
  await loader.reload();
  assert.deepEqual(loader.getExtensions().errors, []);
  const extension = loader.getExtensions().extensions.find((item) => item.tools.has('knowledge_search'));
  assert.deepEqual([...extension.tools.keys()].sort(), [...CHILD_TOOLS].sort());
  assert.equal(extension.commands.size, 0);
  const restricted = await ensureChildEntry({ ...scope, tools: [] }, descriptor);
  assert.notEqual(restricted, path);
  const { default: entry } = await import(pathToFileURL(restricted).href);
  const child = harness([]);
  await entry(child.pi);
  assert.equal(child.tools.size, CHILD_TOOLS.length);
  await child.events.get('session_start')();
  assert.deepEqual(child.active, []);
  assert.throws(
    () => child.tools.get('knowledge_search').execute('id', { collectionIds: ['one'], query: 'test' }),
    /CHILD_TOOL_NOT_AUTHORIZED/
  );
  assert.throws(
    () => child.tools.get('memory_read').execute('id', { refs: [] }),
    /CHILD_TOOL_NOT_AUTHORIZED/
  );
  for (const name of ['ocr_image', 'embed_text', 'rerank_documents']) {
    assert.throws(() => child.tools.get(name).execute('id', {}), /CHILD_TOOL_NOT_AUTHORIZED/);
  }
  child.pi.setActiveTools(['knowledge_search', 'ocr_image', 'embed_text', 'rerank_documents']);
  await child.events.get('before_agent_start')();
  assert.deepEqual(child.active, []);
  await child.events.get('session_shutdown')();
  await ensureExplorerAgent(root);
  const agent = join(root, 'agents', 'octopus-explorer.md');
  const expected = await readFile(agent, 'utf8');
  for (const name of CHILD_TOOLS) assert.ok(expected.includes(name));
  await writeFile(agent, 'old managed version');
  await Promise.all(Array.from({ length: 4 }, () => ensureExplorerAgent(root)));
  assert.equal(await readFile(agent, 'utf8'), expected);
});

test('knowledge entry rejects out-of-scope access before transport and never starts missing service', async () => {
  const root = await mkdtemp(join(tmpdir(), 'octopus-child-knowledge-'));
  const agentDir = join(root, 'agent');
  await mkdir(agentDir);
  const { pi, tools } = harness();
  createKnowledgeChildExtension({
    agentDir,
    workspaceId: 'w',
    collectionIds: ['allowed'],
    tools: [...CHILD_TOOLS],
  })(pi);
  await assert.rejects(
    tools.get('knowledge_search').execute('id', { collectionIds: ['other'], query: 'test' }),
    /集合范围/
  );
  await assert.rejects(
    tools.get('knowledge_search').execute('id', { collectionIds: ['allowed'], query: 'test' }),
    { code: 'KNOWLEDGE_UNAVAILABLE' }
  );
  assert.deepEqual(await readdir(root), ['agent']);
});

test('memory child reads real SQLite, honors off policy and never initializes missing storage', async () => {
  const root = await mkdtemp(join(tmpdir(), 'octopus-child-memory-'));
  const child = harness();
  createMemoryChildExtension({ dataRoot: root })(child.pi);
  const recall = (input = { mode: 'page' }) => child.tools.get('memory_recall').execute('id', input);
  assert.deepEqual((await recall()).details.items, []);
  assert.deepEqual(await readdir(root), []);
  const writer = createMemoryService({ dataRoot: root });
  const receipt = await writer.remember({
    requestId: 'one',
    canonicalKey: 'child.test',
    topic: 'Test',
    type: 'preference',
    indexText: 'Child fact',
    bodyMd: 'Readonly child fact',
    action: 'create',
    sources: [{ sessionId: 'parent', entryId: 'one', evidence: 'Readonly child fact' }],
  });
  assert.equal((await recall()).details.items.length, 1);
  const read = await child.tools.get('memory_read').execute('id', { refs: [receipt.ref] });
  assert.match(JSON.stringify(read.details), /Readonly child fact/);
  const status = await writer.getStatus();
  await writer.setPolicy({ requestId: 'off', mode: 'off', expectedRevision: status.revision });
  await assert.rejects(recall(), { code: 'READ_ONLY' });
  await child.events.get('session_shutdown')();
  await child.events.get('session_shutdown')();
  await writer.dispose();
});

test('delegated execution checks actual paths and never promotes ask or deny to allow', () => {
  for (const [mode, policy, input, error] of [
    ['full', 'deny', { texts: ['one'] }, /CHILD_PERMISSION_DENIED/],
    ['full', 'ask', { texts: ['one'] }, /CHILD_PERMISSION_REQUIRED/],
    ['ask', undefined, { texts: ['one'] }, /CHILD_PERMISSION_REQUIRED/],
    ['full', 'allow', { path: '.ssh/key.png' }, /CHILD_PERMISSION_DENIED/],
  ]) {
    const child = harness();
    const permissions = permissionSnapshot(mode);
    const name = input.path ? 'ocr_image' : 'embed_text';
    if (policy) permissions.configuration.policy.tools[name] = policy;
    createScopedChildExtension({
      agentDir: tmpdir(),
      workspaceId: 'w',
      collectionIds: [],
      tools: [...CHILD_TOOLS],
      permissions,
    })(child.pi);
    assert.throws(
      () => child.tools.get(name).execute('id', input, undefined, undefined, { cwd: process.cwd() }),
      error
    );
  }
});

test('diagnostics explain admission and child allowlists without creating resources', () => {
  const permissions = permissionSnapshot();
  permissions.configuration.policy.tools.ocr_image = 'deny';
  permissions.configuration.policy.tools.embed_text = 'ask';
  const input = {
    permissions,
    cwd: process.cwd(),
    knowledgeEnabled: false,
    activeTools: CHILD_TOOLS.filter((name) => name !== 'memory_read'),
    registeredTools: CHILD_TOOLS.filter((name) => name !== 'memory_recall'),
  };
  const rows = inspectDelegatedTools(input, [...CHILD_TOOLS, 'made_up_tool']);
  const reason = (name) => rows.find((row) => row.name === name).reason;
  assert.equal(reason('ocr_image'), 'permission_deny');
  assert.equal(reason('embed_text'), 'permission_ask');
  assert.equal(reason('rerank_documents'), 'eligible');
  assert.equal(reason('knowledge_search'), 'knowledge_mode_disabled');
  assert.equal(reason('memory_read'), 'parent_tool_inactive');
  assert.equal(reason('memory_recall'), 'parent_tool_missing');
  assert.equal(reason('made_up_tool'), 'not_delegatable');
  assert.equal(
    inspectDelegatedTools({ ...input, childTools: [] }, ['rerank_documents'])[0].reason,
    'child_allowlist_excluded'
  );
});

test('delegation configuration contains unique names with real registered implementations', () => {
  assert.equal(new Set(CHILD_TOOLS).size, CHILD_TOOLS.length);
  const child = harness();
  createScopedChildExtension({
    agentDir: tmpdir(),
    workspaceId: 'w',
    collectionIds: [],
    tools: [],
    permissions: permissionSnapshot(),
  })(child.pi);
  assert.deepEqual([...child.tools.keys()].sort(), [...CHILD_TOOLS].sort());
  assert.equal(child.commands.size, 0);
});

test('parent diagnostics reuse the current permission mode without loading child resources', async () => {
  const parent = harness();
  const service = fullPermissions();
  createSubagentBridgeExtension(
    { agentDir: tmpdir(), workspaceId: 'w', permissionService: service },
    {
      loadRequiredChildApi: async () => assert.fail('must not load child API'),
      ensureExplorerAgent: async () => assert.fail('must not write agent'),
      ensureChildEntry: async () => assert.fail('must not write entry'),
    }
  )(parent.pi);
  const notifications = [];
  const ctx = {
    hasUI: true,
    ui: { notify: (message) => notifications.push(message) },
    cwd: process.cwd(),
    isProjectTrusted: () => false,
    sessionManager: { getBranch: () => [] },
  };
  const inspect = async () => {
    await parent.commands.get('subagent-tools').handler('embed_text', ctx);
    return JSON.parse(parent.messages.at(-1).content).tools[0];
  };
  assert.equal((await inspect()).reason, 'eligible');
  service.setMode('ask');
  assert.equal((await inspect()).reason, 'permission_ask');
  assert.deepEqual(notifications, ['子代理工具诊断完成', '子代理工具诊断完成']);
});

test('every child loader rejects stale authority and refreshes admission without parent tool_call', async () => {
  const parent = harness();
  const service = fullPermissions();
  const entries = [];
  let branch = [];
  const ctx = {
    cwd: process.cwd(),
    isProjectTrusted: () => false,
    sessionManager: {
      getBranch: () => branch,
      getSessionId: () => 'admission',
      getSessionFile: () => undefined,
    },
  };
  createSubagentBridgeExtension(
    { agentDir: tmpdir(), workspaceId: 'w', permissionService: service },
    {
      loadRequiredChildApi: async () => ({ registerRequiredChildExtensions: () => ({ dispose() {} }) }),
      ensureExplorerAgent: async () => {},
      ensureChildEntry: async (scope, admission) => {
        entries.push({ scope, admission });
        return '/fixture.mjs';
      },
    }
  )(parent.pi);
  await parent.events.get('session_start')({}, ctx);
  try {
    const initial = entries.at(-1).admission;
    await verifyChildAdmission(initial);
    // Slash commands and the structured API do not emit parent tool_call.
    service.setMode('ask');
    await assert.rejects(verifyChildAdmission(initial), /CHILD_SCOPE_STALE/);
    assert.equal(entries.at(-1).scope.permissions.mode, 'ask');
    assert.equal(entries.at(-1).scope.tools.includes('ocr_image'), false);
    const current = entries.at(-1).admission;
    await verifyChildAdmission(current);
    branch = [{ type: 'custom', customType: 'octopus-knowledge-mode', data: {} }];
    await assert.rejects(verifyChildAdmission(current), /CHILD_SCOPE_STALE/);
    branch = [];
    await verifyChildAdmission(current); // Recovery does not require a parent tool_call.
    await assert.rejects(verifyChildAdmission({ ...current, token: '0'.repeat(64) }), /CHILD_SCOPE_STALE/);
    parent.active.splice(0, parent.active.length);
    await assert.rejects(verifyChildAdmission(current), /CHILD_SCOPE_STALE/);
    assert.deepEqual(entries.at(-1).scope.tools, []);
  } finally {
    await parent.events.get('session_shutdown')();
  }
  await assert.rejects(verifyChildAdmission(entries.at(-1).admission), /CHILD_ADMISSION_UNAVAILABLE/);
});
