/**
 * @author Codex
 * @description Owns Pi Session history, offline derivation, model projection, and exported artifact reads.
 */

import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { responseData } from './utils.js';
import type { DerivedPiSession, PiSessionRepository } from './pi-session-repository.js';
import type { ManagedSessionCommand } from './types.js';
import type { SessionEntry } from '@earendil-works/pi-coding-agent';

export interface RuntimeModel {
  provider: string;
  id: string;
  name: string;
  reasoning: boolean;
  input: Array<'text' | 'image'>;
  contextWindow?: number;
}

export interface RuntimeArtifactsOptions {
  piSessions: PiSessionRepository;
  /**
   * Executes an artifact-related command through the owning runtime operation boundary.
   */
  execute: (sessionId: string, command: ManagedSessionCommand) => Promise<unknown>;
}

/**
 * Keeps Pi persistence and artifact-specific projections out of the main Sessions orchestration file.
 */
export class RuntimeArtifacts {
  readonly #piSessions: PiSessionRepository;
  readonly #execute: RuntimeArtifactsOptions['execute'];

  /**
   * Creates artifact operations over Pi Session persistence and managed runtime commands.
   */
  public constructor(options: RuntimeArtifactsOptions) {
    this.#piSessions = options.piSessions;
    this.#execute = options.execute;
  }

  /**
   * Reads append-order Session entries after an optional durable cursor.
   */
  public getEntries(sessionPath: string, since?: string): { entries: SessionEntry[]; leafId: string | null } {
    return this.#piSessions.getEntries(sessionPath, since);
  }

  /**
   * Reads the current root-to-leaf branch for extension state projection.
   *
   * @param sessionPath Pi Session JSONL path.
   * @returns Entries reachable from the active leaf.
   */
  public getBranch(sessionPath: string): SessionEntry[] {
    return this.#piSessions.getBranch(sessionPath);
  }

  /**
   * Reads the authoritative Session tree and leaf.
   */
  public getTree(sessionPath: string): ReturnType<PiSessionRepository['getTree']> {
    return this.#piSessions.getTree(sessionPath);
  }

  /**
   * Removes the raw Pi Session JSONL file when the control-plane record is already gone.
   */
  public async deleteSessionFiles(sessionPath: string): Promise<void> {
    await this.#piSessions.delete(sessionPath);
  }

  /**
   * Derives a dormant Session without replacing or stopping the source runtime.
   */
  public async deriveSession(
    sessionPath: string,
    mode: 'fork' | 'clone',
    entryId?: string
  ): Promise<DerivedPiSession> {
    return this.#piSessions.derive(sessionPath, mode, entryId);
  }

  /**
   * Projects Pi model records onto browser-stable model DTOs.
   */
  public async getModels(sessionId: string): Promise<RuntimeModel[]> {
    const response = await this.#execute(sessionId, { type: 'get_available_models' });
    return this.projectModels(response);
  }

  /**
   * Projects an already acquired Pi model response without opening another Runtime operation.
   *
   * @param response Pi get_available_models response envelope.
   * @returns Browser-stable Runtime model records.
   */
  public projectModels(response: unknown): RuntimeModel[] {
    const data = responseData<{ models?: Array<Record<string, unknown>> }>(response);
    return (data?.models ?? []).map((model) => ({
      provider: modelString(model['provider']),
      id: modelString(model['id']),
      name: modelString(model['name'], modelString(model['id'])),
      reasoning: Boolean(model['reasoning']),
      input: Array.isArray(model['input']) ? (model['input'] as Array<'text' | 'image'>) : ['text'],
      ...(typeof model['contextWindow'] === 'number' ? { contextWindow: model['contextWindow'] } : {}),
    }));
  }

  /**
   * Produces and reads one HTML export through a Host-owned temporary path.
   *
   * @param sessionId Stable Web Session identity.
   * @returns Standalone HTML generated by Pi for the active Session branch.
   */
  public async exportHtml(sessionId: string): Promise<string> {
    const exportDirectory = await mkdtemp(join(tmpdir(), 'dr-octopus-export-'));
    const outputPath = join(exportDirectory, 'session.html');
    try {
      const response = await this.#execute(sessionId, { type: 'export_html', outputPath });
      const data = responseData<{ path?: string }>(response);
      if (data?.path === undefined) {
        throw new Error('Pi did not return an export path.');
      }
      return await readFile(outputPath, 'utf8');
    } finally {
      await rm(exportDirectory, { recursive: true, force: true });
    }
  }
}

/**
 * Coerces optional Pi model fields into stable strings.
 */
function modelString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}
