/**
 * @author Codex
 * @description Installs only the frozen release dependency graph and probes native modules in an isolated process.
 */
import { access, mkdir, readFile } from 'node:fs/promises';
import { dirname, join, relative, isAbsolute } from 'node:path';
import { getGatewayStatus, gatewayError } from './gateway/index.js';
import { execute } from './process.js';
import { releaseRoot, releasePaths } from './paths.js';
import { progress } from './output.js';
import { acquireKnowledgeReleaseInstallGuard, assertSchedulerReleaseIdle } from './release-use.js';
import { cliCommand, distribution } from './distribution/location.js';
import { runtimePnpm } from './distribution/pnpm.js';
import { prepareRuntime } from './distribution/payload.js';
import { acquireInstallLock } from './distribution/install-lock.js';
import { confirmDependencyInstall } from './dependency-prompt.js';
import {
  effectiveRegistry,
  installationFailure,
  redactInstallOutput,
  registryUrl,
} from './install-registry.js';
import type { OutputOptions } from './output.js';

export interface ReleaseManifest {
  version: string;
  packageManager: string;
}

export interface DependencyOptions extends OutputOptions {
  installDeps?: boolean;
  yes?: boolean;
  registry?: string;
}

/**
 * Reads original workspace metadata and checks the CLI bootstrap before installing dependencies.
 */
export async function readRelease(root = releaseRoot()): Promise<ReleaseManifest> {
  const context = distribution();
  if (context.packaged && (await readFile(join(root, '.payload-sha256'), 'utf8')) !== context.layout.sha256) {
    throw gatewayError('RELEASE_INVALID', 'Runtime payload identity differs from this npm package.');
  }
  const manifest = JSON.parse(await readFile(join(root, 'package.json'), 'utf8')) as ReleaseManifest;
  if (!manifest.packageManager?.startsWith('pnpm@')) {
    throw gatewayError('RELEASE_INVALID', 'Use a workspace release generated by pnpm release.');
  }
  for (const resource of ['pnpm-lock.yaml', 'pnpm-workspace.yaml']) {
    await access(join(root, resource));
  }
  const paths = releasePaths(root);
  await access(paths.serverEntry);
  await access(paths.gatewayEntry);
  await access(join(paths.webClient, 'index.html'));
  return manifest;
}

/**
 * Verifies dependency resolution and native execution without initializing Server, extensions or Scheduler.
 */
export async function verifyDependencies(root = releaseRoot()): Promise<void> {
  try {
    await readRelease(root);
    await execute(
      process.execPath,
      [
        '--input-type=module',
        '--eval',
        `
      import { createRequire } from 'node:module';
      import { realpathSync } from 'node:fs';
      import { relative, isAbsolute } from 'node:path';
      import { fileURLToPath } from 'node:url';
      const require = createRequire(process.cwd() + '/package.json');
      for (const specifier of ['@octopus/agent', '@octopus/agent/rpc', '@octopus/shared/protocol']) {
        const path = realpathSync(fileURLToPath(import.meta.resolve(specifier)));
        const rel = relative(${JSON.stringify(root)}, path);
        if (rel.startsWith('..') || isAbsolute(rel)) throw new Error('Dependency escapes workspace: ' + specifier);
      }
      const Database = require('better-sqlite3');
      const db = new Database(':memory:'); db.prepare('SELECT 1').get(); db.close();
      const sharp = require('sharp'); await sharp({create:{width:1,height:1,channels:3,background:'#fff'}}).png().toBuffer();
      require('@napi-rs/canvas').createCanvas(1,1).toBuffer('image/png');
      require('pino-pretty');
      const cliRequire = createRequire(${JSON.stringify(join(releasePaths(root).cli, 'package.json'))});
      cliRequire('koffi');
    `,
      ],
      releasePaths(root).server
    );
  } catch (error) {
    throw gatewayError('DEPENDENCIES_UNAVAILABLE', `Run ${cliCommand()} deps install. ${String(error)}`);
  }
}

/**
 * Installs the release-local frozen graph without invoking extension installation or service startup.
 */
export async function installDependencies(
  options: DependencyOptions,
  root = releaseRoot()
): Promise<{ installed: true; directory: string }> {
  const context = distribution();
  if (options.registry !== undefined) {
    registryUrl(options.registry);
  }
  if (!context.packaged) {
    throw gatewayError(
      'DEVELOPMENT_WORKSPACE',
      'Use pnpm install and pnpm build in the development workspace.'
    );
  }
  await mkdir(dirname(root), { recursive: true, mode: 0o700 });
  const unlock = await acquireInstallLock(root);
  const indicator = progress(options, `Installing runtime dependencies in ${root}`);
  let releaseKnowledgeGuard: (() => void) | undefined;
  try {
    releaseKnowledgeGuard = await acquireKnowledgeReleaseInstallGuard(
      root,
      join(root, context.layout.paths.cli)
    );
    const status = await getGatewayStatus();
    const gatewayEntry = status ? relative(root, status.entryPath) : undefined;
    if (gatewayEntry !== undefined && !gatewayEntry.startsWith('..') && !isAbsolute(gatewayEntry)) {
      throw gatewayError('RELEASE_IN_USE', 'Stop this release Gateway before installing dependencies.');
    }
    const pnpm = await runtimePnpm();
    await prepareRuntime(context, root);
    await readRelease(root);
    await assertSchedulerReleaseIdle(root);
    const registry = await effectiveRegistry(pnpm, root, options.registry);
    indicator.message(`Registry: ${redactInstallOutput(registry)}`);
    try {
      await execute(
        pnpm.command,
        [
          ...pnpm.args,
          '--filter-prod',
          context.layout.installFilter,
          'install',
          '--prod',
          '--frozen-lockfile',
          ...(options.registry ? ['--registry', registry] : []),
        ],
        root,
        true,
        900_000,
        redactInstallOutput
      );
    } catch (error) {
      throw installationFailure(error, registry, cliCommand(), Boolean(options.registry));
    }
    indicator.message('Verifying runtime and native modules');
    await verifyDependencies(root);
    indicator.stop('Runtime dependencies verified');
    return { installed: true, directory: root };
  } catch (error) {
    indicator.stop('Dependency installation failed');
    throw error;
  } finally {
    releaseKnowledgeGuard?.();
    await unlock();
  }
}

/**
 * Reuses actual runtime validation; only packaged startup may ask or explicitly auto-install dependencies.
 */
export async function ensureDependencies(options: DependencyOptions): Promise<void> {
  if (options.registry !== undefined) {
    registryUrl(options.registry);
  }
  try {
    await verifyDependencies();
    return;
  } catch (error) {
    if (!distribution().packaged) {
      throw error;
    }
  }
  if (!options.installDeps && !options.yes) {
    if (options.json || !process.stdin.isTTY || !process.stderr.isTTY) {
      throw gatewayError(
        'DEPENDENCIES_UNAVAILABLE',
        `Run ${cliCommand()} deps install or pass --install-deps / --yes.`
      );
    }
    let registry = options.registry;
    if (!registry) {
      const root = await access(releaseRoot()).then(
        () => releaseRoot(),
        () => distribution().root
      );
      try {
        registry = await effectiveRegistry(await runtimePnpm(), root);
      } catch {
        // Consent must remain available even when the bootstrap pnpm installation needs repair.
      }
    }
    if (!(await confirmDependencyInstall(registry ? redactInstallOutput(registry) : undefined))) {
      throw gatewayError(
        'INSTALL_DECLINED',
        `Dependencies were not installed. Run ${cliCommand()} deps install when ready.`
      );
    }
  }
  await installDependencies(options);
}
